import { Geist, Geist_Mono, Poppins } from "next/font/google";
import Image from "next/image"; // Import Next.js Image
// import Banner from '../../../public/banner.png'; // Import your banner
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";

// Existing fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Add Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "swiftdeliver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <NextIntlClientProvider>
          {/* Banner Image */}
          {/* <div className="relative w-full h-64">
            <Image
              src={Banner}
              alt="Banner"
              fill
              style={{ objectFit: "cover" }}
            />
          </div> */}

          {/* Rest of the content */}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
