import { Geist, Geist_Mono, Poppins } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { useSearchParams } from "next/navigation"; // Next.js hook to read query params
import Banner from "../../../public/banner.png"; // Your banner image

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "swiftdeliver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Use Next.js hook to get URL search params
  const searchParams = useSearchParams();
  const showBanner = searchParams.get("banner") === "true"; // example: ?banner=true

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <NextIntlClientProvider>
          {showBanner && (
            <div className="w-full relative h-60 mb-4">
              <Image
                src={Banner}
                alt="Banner"
                fill
                style={{ objectFit: "cover" }}
              />
            </div>
          )}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
